#!/usr/bin/env php
<?php

error_reporting(E_ALL | E_STRICT);

echo '================================================================================' . PHP_EOL;
echo 'Initializing PHP_CodeSniffer "installed_paths"...' . PHP_EOL;
echo PHP_EOL;

// Script path: "./vendor/bin/sms-phpcs-init" or "./scripts/sms-phpcs-init"
$baseDir = realpath(__DIR__ . '/../../../');
$vendorDir = $baseDir . '/vendor';
$csPath = $vendorDir . '/smstw/php-code-sniffer';

if (!is_dir($vendorDir))
{
	$baseDir = realpath(__DIR__ . '/../');
	$vendorDir = $baseDir . '/vendor';
	$csPath = dirname($baseDir);

	if (!is_dir($vendorDir))
	{
		throw new Exception('no vendor path found');
	}
}

require $vendorDir . '/autoload.php';

$phpcs = new \PHP_CodeSniffer();

$paths = $phpcs->getInstalledStandardPaths();
$paths[] = $csPath;

$paths = array_unique($paths);

$phpcs->setConfigData('installed_paths', implode(',', $paths));

echo '"installed_paths" as below:' . PHP_EOL;

foreach ($paths as $path)
{
	echo '  - ' . $path . PHP_EOL;
}

echo PHP_EOL;
echo 'Initializing PHP_CodeSniffer complete.' . PHP_EOL;
echo '================================================================================' . PHP_EOL;
